server:
    port: 8090

spring:
    application:
        name: CapabilitiesService

    r2dbc:
        url: r2dbc:mysql://localhost:3306/capabilities-db
        username: root
        password: root
        pool:
            enabled: true

    sql:
        init:
            mode: always
            platform: mysql